@startuml
<style>
    title {
      HorizontalAlignment center
      FontSize 18
      padding 20
    }
</style>

'Doubts: Should communication between components be verbose?
title Use Case - List Devices Grouped By Functionality \nProcess View Level 3 - Backend Interaction \n Main Success Scenario
autonumber

participant "**<<component (C4)>>**\nServer" as SERVER
participant "**<<component (C4)>>**\nDatabase" as DB

[o-> SERVER : List all devices grouped by functionality
activate SERVER

SERVER -> DB: Find all sensors
activate DB
DB --> SERVER: Retrieve sensor list
deactivate DB
|||
SERVER -> DB: Find all actuators
activate DB
DB --> SERVER: Retrieve actuator list
deactivate DB
|||
SERVER -> SERVER : Group devices \nby functionality


[o<-- SERVER : Successful Operation.\nRetrieve devices information \ngrouped by functionality
deactivate SERVER

@enduml