@startuml
<style>
    title {
      HorizontalAlignment center
      FontSize 18
      padding 20
    }
</style>

'Doubts: Should communication between components be verbose?
title Use Case - Deactivate a Device\nProcess View Level 3 - Backend Interaction \n Main Success Scenario
autonumber

participant "**<<component (C4)>>**\nServer" as SERVER
participant "**<<component (C4)>>**\nDatabase" as DB

[o-> SERVER : Deactivate this device
activate SERVER

SERVER -> DB: Verify if device exists
activate DB
DB --> SERVER: Send validation
deactivate DB
|||
SERVER -> SERVER : Verify if device is active
|||
SERVER -> SERVER : Deactivate device
|||
SERVER -> DB: Save device with updated status
activate DB
DB --> SERVER: Send validation
deactivate DB

[o<-- SERVER : Successful Operation.\nRetrieve device \
 information \nwith updated status
deactivate SERVER

@enduml