@startuml
<style>
    title {
      HorizontalAlignment center
      FontSize 18
      padding 20
    }
</style>

'Doubts: Should communication between components be verbose?
title Use Case - Close a Roller Blind\nProcess View Level 3 - Backend Interaction \n Main Success Scenario
autonumber

participant "**<<component (C4)>>**\nServer" as SERVER
participant "**<<component (C4)>>**\nDatabase" as DB


[o-> SERVER : Use this actuator ID to close a roller blind
activate SERVER

SERVER -> DB: Verify if actuator exists
activate DB
DB --> SERVER: Send validation
deactivate DB
|||
SERVER -> DB: Get actuator by its id
activate DB
DB --> SERVER: Retrieve actuator
deactivate DB
|||
SERVER -> SERVER : Validate actuator type
|||
SERVER ->o]: Close roller blind
note right: **Currently, the interaction with physical **\n**devices is just an abstraction.**

SERVER <--o]: Send validation


[o<-- SERVER : Successful Operation.
deactivate SERVER

@enduml