@startuml

title Use Case - List Existing Room \nProcess View Level 2 \n Success Scenario
/'
As a Room Owner [or Power User, or Administrator], I want to get a list of all
devices in a room.
'/
autonumber

participant "**<<container (C4)>>**\nBackend" as BE


[o-> BE: List all rooms in the house
activate BE
[o<-- BE: Provide a list of all rooms
deactivate BE


@enduml
